version: '3'
services:

  my-app:
    build: .
    # image: docker-hub-user/image-name:image-tag
    ports:
     - 3000:3000
    environment:
     - MONGO_DB_USERNAME=admin
     - MONGO_DB_PWD=12345

  mongodb:
    image: mongo
    container_name: c_mongo
    ports:
     - 27018:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=12345

  mongo-express:
    image: mongo-express
    container_name: c_mongo-express
    restart: always
    ports:
     - 8085:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"