version: '3'
services:

  mongodb:
    image: mongo
    container_name: c_mongo3
    restart: always
    ports:
     - 9005:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: c_mongo-express3
    restart: always
    ports:
     - ${PORT}:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${USERNAME}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"