version: '3'
services:

  mongodb:
    image: mongo
    container_name: c_mongo3
    restart: always
    ports:
     - 9005:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - db:/data/db

  mongo-express:
    image: mongo-express
    container_name: c_mongo-express3
    restart: always
    ports:
     - ${PORT}:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
  


volumes:
    db: